### ISSUE TITLE
[CWM] Build Directory and Search Panels

### ISSUE THREAD

**Issue by ms0ur1s** [DigitalCommons/mykomap#272]
## Description

We need to build the directory and search panels based on the designs outlined in [issue #264](https://github.com/DigitalCommons/mykomap/issues/264). These panels consist of multiple components, which can be broken down into separate issues if necessary. However, for now, all components will be tracked within this issue as individual tasks (checkboxes). Each task can be completed independently following @rogup's recommended [trunk-based development](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development) workflow.

This issue also includes the integration of Storybook.js into the development process and the implementation of mock data for specific components, such as the 'Select box' in the filter panel and the 'Result item' in the results panel.

**Component Tree Schematic:**
```
    ComponentContainer Panel (shared)
        Component Heading component
        Component Close button (shared), (mobile)
        Component Close tab (shared), (desktop)
        Component Search box
        ComponentContainer Directory panel
            Component Directory item
        ComponentContainer Filter panel
            Component Select box (shared)
            Component Button (shared)
        ComponentContainer About panel
            Component Rich text / markdown display panel

    ComponentContainer Results panel
        Component Close button (shared), (mobile)
        Component Close tab (shared), (desktop)
        Component Button (shared)
        Component Result item

    ComponentContainer Menu bar
        Component Menu item
```

## Tasks

**1. Set up Storybook.js integration**
   -  Integrate Storybook.js into the project workflow to allow for isolated development and testing of components.
   -  Ensure that each component listed below has a corresponding Storybook entry.

**2. Create Shared Components**
   - [x] Panel ComponentContainer
   - [x] Close button (shared), (mobile)
   - [x] Panel toggle button (shared), (desktop)
   - [x] Button (shared)
   - [x] Select box (shared)
   - [x] Heading component

**3. Create Panel Component**
   - [x] Integrate 'Panel', 'Heading',  'Close button' and 'Panel toggle button' components

**4. Build Directory Panel Components**
   - [x] Directory panel ComponentContainer
   - [x] Directory item 

**5. Build Filter Panel Components**
   - [x] Filter panel ComponentContainer
   - [x] Integrate 'Select box' and 'Button' components
   - [x] Create 'Search box' component and integrate with Filter Panel

**6. Build About Panel Components**
   - [x] About panel
   - [x] Rich text / markdown display component

**7. Build Results Panel Components**
   - [x] Results panel ComponentContainer
   - [x] Result item Component
   - [x] Integrate 'Close button', 'Close tab' and 'Button components'

**8. Build  Menu Bar Components**
   - [x] Menu bar ComponentContainer
   - [x] Menu item Component

**9. Mock Data Integration**
   - Implement a mock data strategy for the Select box components in the Filter panel.
   - Implement mock data for the Result item components in the Results panel.
   - Ensure that Storybook includes these mocks to allow for realistic component previews.

_Added 12/09/24_
**10.  Create app theme**
   - [x] Create theme for consistent look across the application

## Acceptance Criteria
- All components listed above are implemented according to the Adobe XD prototypes.
- Storybook.js is fully integrated, with all components available for viewing and interaction.
- Mock data is successfully implemented for the Select box and Result item components.
- Components are responsive and adhere to design specifications across mobile and desktop.

**Comment by ms0ur1s** [comment]
### Adobe XD Prototypes
[https://xd.adobe.com/view/0f8c7d84-e063-4008-a2fb-c7e3b8580d07-5adf/](https://xd.adobe.com/view/0f8c7d84-e063-4008-a2fb-c7e3b8580d07-5adf/)
[https://xd.adobe.com/view/4ed77098-5133-4b80-b34c-2f2b3e5b22a7-1b84/](https://xd.adobe.com/view/4ed77098-5133-4b80-b34c-2f2b3e5b22a7-1b84/)

**Comment by rogup** [comment]
This plan looks sick!

**Comment by ms0ur1s** [comment]
> This plan looks sick!

Thanks @rogup, should I create these components within the [mykomap-react](https://github.com/DigitalCommons/mykomap-react) repo?

**Comment by rogup** [comment]
> > This plan looks sick!
> 
> Thanks @rogup, should I create these components within the [mykomap-react](https://github.com/DigitalCommons/mykomap-react) repo?

@ms0ur1s That project has been closed and migrated to a sub-app of https://github.com/DigitalCommons/mykomap-monolith

So you'll need to clone mykomap-monolith, then make changes to the `front-end` app, either directly to `main` if they're small or in small PRs. Note that the monorepo uses npm workspaces, so there's a particular way of installing packages with the `-w` option (see the root README). If that doesn't make sense or you have questions, happy to do a quick walkthrough on a call tomorrow morning 😊

**Comment by ms0ur1s** [comment]
> @ms0ur1s That project has been closed and migrated to a workspace within https://github.com/DigitalCommons/mykomap-monolith
> 
> So you'll need to clone mykomap-monolith, then make changes to the `front-end` app, either directly to `main` if they're small or in small PRs. Note that the monorepo uses npm workspaces, so there's a particular way of installing packages with the `-w` option (see the root README). If that doesn't make sense or you have questions, happy to do a quick walkthrough on a call tomorrow morning 😊

Thanks @rogup, I'll clone the mykomap-monolith and I'll give you a shout if (when) I get stuck.

**Comment by ms0ur1s** [comment]
### PR that merges 15 - 20 tasks into main 
https://github.com/DigitalCommons/mykomap-monolith/pull/18

**Comment by ms0ur1s** [comment]
### PR for panel width update
https://github.com/DigitalCommons/mykomap-monolith/pull/28

**Comment by ColmDC** [comment]
@ms0ur1s as the design of the Data Source filter generated some confusion. I confirm here that we are going with the simplest option first. We only have one dropdown that relates to Data Sources, and it should be called Data Sources rather than Apex Organisations. It's default is - Any- as with other filters. When selected the drop down will show all the data sources which have been merged for this instance of the CWM. Only one can be selected at a time and if one is selected it will filter out all the co-ops which do not have an entry in the selected data set. Clearing Filters or resetting the dropdown option to -Any- will return to displaying co-ops from all the data sources.

**Comment by rogup** [comment]
@ColmDC If I correctly understand the design that was eventually decided, which I reviewed a while ago, the search results list on mobile is effectively the same as ListView. I think the toggle was there to make the UX less confusing to navigate between the map and the list of results. But maybe in this iteration, this view could be simplified (e.g. a list of co-op titles on a plain black background, like the current results view)?
Does that make sense @ms0ur1s or maybe I misunderstood the design?

**Comment by ColmDC** [comment]
I think my feedback (which was trying to simplify the paths and lighten the workload for Delhi) didn't make it into the mockups. I think I just need @ms0ur1s to walk me through the mockups and explain his thinking.

**Comment by ColmDC** [comment]
In the same spirit as the Data Source drop down decision, let's implement whatever is the easiest to get to a minimal demo version.

**Comment by ms0ur1s** [comment]
> @ms0ur1s as the design of the Data Source filter generated some confusion. I confirm here that we are going with the simplest option first. We only have one dropdown that relates to Data Sources, and it should be called Data Sources rather than Apex Organisations. It's default is - Any- as with other filters. When selected the drop down will show all the data sources which have been merged for this instance of the CWM. Only one can be selected at a time and if one is selected it will filter out all the co-ops which do not have an entry in the selected data set. Clearing Filters or resetting the dropdown option to -Any- will return to displaying co-ops from all the data sources.

This makes sense for the first iteration of the app.

**Comment by ms0ur1s** [comment]
> I also wanted to make clear here that we are not implementing the ListView path in this iteraction of the project. We have discussed this, but it didn't seem to make it into the design or implementation tickets. So no need for the MapView/ListView toggle at the top of the map for this ticket.

That's what I understood from our previous conversation.

**Comment by ms0ur1s** [comment]
> @ColmDC If I correctly understand the design that was eventually decided, which I reviewed a while ago, the search results list on mobile is effectively the same as ListView. I think the toggle was there to make the UX less confusing to navigate between the map and the list of results. But maybe in this iteration, this view could be simplified (e.g. a list of co-op titles on a plain black background, like the current results view)? Does that make sense @ms0ur1s or maybe I misunderstood the design?

Hi @rogup, I think that would have been the case if we were implementing ListView, but it's easier just to supply a responsive version of the desktop search results. Which is how thing currently stand. 

![image](https://github.com/user-attachments/assets/bf39652c-ea04-42e4-b793-3a2a817c6b0d)

**Comment by ms0ur1s** [comment]
> I think my feedback (which was trying to simplify the paths and lighten the workload for Delhi) didn't make it into the mockups. I think I just need @ms0ur1s to walk me through the mockups and explain his thinking.

Hi @ColmDC, see my above reply to @rogup.

**Comment by rogup** [comment]
The branch for this has been reviewed and merged now (PR 38) so I think this is done? @ms0ur1s

**Comment by ms0ur1s** [comment]
> The branch for this has been reviewed and merged now (PR 38) so I think this is done? @ms0ur1s

I missed a task for combining / linking the main panel to the search results. This only the only thing outstanding.
